[features]
seeds = false
[programs.localnet]
nfpics = "33dzo1WrFP7udfrHBxkEGDzrTFj3F2w1cMePKjNtsWnr"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/reljodoreta/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
